name: ci - Lint Code
run-name: ${{ github.ref_name }} - Checking code of ${{ github.actor }}
on:
  push:
  pull_request:
jobs:
  ci:
    name: CI - Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.2.0
        with:
          run_install: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint - tsc
        run: pnpm run ci:tsc

      - name: Run lint - biome
        run: pnpm run ci:biome
